# ベースイメージ
FROM golang:1.22

# 作業ディレクトリを設定
WORKDIR /app

# モジュールのコピー
COPY go.mod go.sum ./
RUN go mod download

# ソースコードをコピー
COPY . .

# Ginアプリケーションをビルド
RUN go build -o main .

# アプリケーションを実行
CMD ["./main"]

# 使用するポートを指定
EXPOSE 8080